[global]
# info = [ {tag="mameversion", value="0229"} ]
author=["jotego"]

[parse]
sourcefile=[ "segas16b.cpp" ]
# Games with S16A parents need explicit listing
# the description is used to make the alternate folders
parents= [
    {name="shinobi", description="Shinobi"},
    {name="afighter", description="Action Fighter"},
    {name="sdi", description="SDI"},
    {name="tetris", description="Tetris"}
]

main_setnames=["tturfu"]

[parse.skip]
descriptions = [ "16A", "Taito" ]
setnames = [
    # untested
    "dddoor",
    # won't boot
    "aceattac", # one S16A set works
    # Boots in service mode and needs custom firmware
    "tturf",
    # new ones to check
    "wfishing",
    # Korean
    "atomicp",
    "lockonph",
    "snapper",
    "dfjail", # boots, unmapped inputs, bad GFX
]

machines = [
    # controls not mapped
    "hwchamp",
    "ultracin",
]
bootlegs = true

[Audio]
volume = [
    { machine="aliensyn", value=0x92 },
    { machine="altbeast", value=0xFF },
    { machine="afighter", value=0xFF },
    { machine="aurail", value=0xF4 },
    { machine="bayroute", value=0x8F },
    { machine="bullet", value=0xF3 },
    { machine="cotton", value=0x70 },
    { machine="dunkshot", value=0xA0 },
    { machine="ddux", value=0xA9 },
    { machine="eswat", value=0xFF },
    { machine="exctleag", value=0xC2 },
    { machine="fantzn2", value=0xFF },
    { machine="fpoint", value=0xFF },
    { machine="goldnaxe", value=0xA3 },
    { machine="mvp", value=0xF1 },
    { machine="riotcity", value=0xFC },
    { machine="ryukyu", value=0xFF },
    { machine="sonicbom", value=0xAD },
    { machine="suprleag", value=0xF2 },
    { machine="timescan", value=0xE1 },
    { machine="toryumon", value=0xFF },
    { machine="tturfu", value=0x8A },
    { machine="wb3", value=0xEE },
    { setname="wb32", value=0xFF },
    { setname="wb33", value=0xFF },
    { setname="wb34", value=0xFF },
    { machine="wrestwar", value=0x9C },
]

[buttons]
#Sega System 16B
#Sega System 16B - Charon
#Sega System 16C
#Sega System 16B - Korean
names = [
    { machine="aceattac", names="none" },
    { machine="afighter", names="Shot,Special Weapon" },
    { setname="afightere",names="Shot,Weapon A, Weapon B, Weapon C" },
    { setname="afighterf",names="Shot,Weapon A, Weapon B, Weapon C" },
    { machine="aliensyn", names="Shot" },
    { machine="altbeast", names="Punch,Kick,Jump" },
    { machine="aurail",   names="Rapid Shot,Kite/Turn,Shield" },
    { machine="bayroute", names="Shot,Jump,Select" },
    { machine="bullet",   names="Shot (Up),Shot (Right),Shot (Behind),Shot (Left)" },
    { machine="cotton",   names="Shoot/Magic,Bomb/Nymphs" },
    { machine="ddux",     names="Shot,Jump" },
    { machine="dunkshot", names="Shot,Pass" },
    { machine="eswat",    names="Shot,Jump,Special Weapons" },
    { machine="exctleag", names="Change,Select,Chase" },
    { machine="fpoint",   names="Rotate,Rotate,Rotate" },
    { machine="goldnaxe", names="Attack,Jump,Magic" },
    { machine="hwchamp",  names="none" },
    { machine="mvp",      names="Change,Select,Chase" },
    { machine="passsht",  names="Flat,Slice,Lob,Top Spin" },
    { machine="riotcity", names="Attack,Jump" },
    { machine="ryukyu",   names="Cancel,Decide" },
    { machine="sdi",      names="Shot" },
    { machine="sonicbom", names="Shot,Super Shot" },
    { machine="shinobi",  names="Shuriken,Jump,Magic" },
    { machine="sjryuko",  names="none" },
    { machine="suprleag", names="Change,Select,Chase" },
    { machine="tetris",   names="Rotate,Rotate,Rotate" },
    { machine="timescan", names="L. Flipper/Ball Start,R. Flipper/Lane Shift" },
    { machine="toryumon", names="Block Turn" },
    { machine="tturf",    names="Punch,Kick,Jump" },
    { machine="ultracin", names="Attack" },
    { machine="wb3",      names="Shot,Jump" },
    { machine="wrestwar", names="Punch,Kick" },
    { machine="fantzn2x", names="Shot,Bomb" },
    { machine="atomicp",  names="Rotate" },
    { machine="snapper",  names="Left,Right,Shot" },
    { machine="lockonph", names="Shot,Bomb" },
    { machine="dfjail",   names="Assault Rifle,Jump,R.P.G" }
]

[dipsw]
delete = [
    { names=[ "Unused", "Unknown", "Advertise Coin Indication" ] },
    { machine="goldnaxe", names=["Difficulty"] },
    { machine="timescan", names=["Coin A", "Coin B"] }, # wouldn't fit in the Pocket
]
bitcnt = 16
rename = [
    { name="Bonus Life", to="Bonus" },
    { name="Extended Score", to="Bonus" },
    { name="Continues", to="Cont." },
    { name="Advertise Sound Interval", to="Demo Sounds" },
    { name="VS Time", to="VS Time", values=[ "shorter","short","long","longer"]},
    { name="CPU Starts With +6 Pts.", to="CPU +6 Pts" },
]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu",       width=16, reverse=true },
    { name="mcu",           start="MCU_START", len=0x1000, custom={ dev="i8751" } },
    { name="soundcpu",      start="JTFRAME_BA1_START" },

    # only three large ROM files
    { name="gfx1",          start="JTFRAME_BA2_START", width=32, sequence=[0,1,2,2] },
    # six smaller ROM files
    { name="gfx1",          start="JTFRAME_BA2_START", frac={ bytes=1, parts=4}, sequence=[0,2,4,4,1,3,5,5], len=0x100000, setnames=[
        "altbeastj",
        "altbeastj3",
        "altbeastj3d",
        "altbeast4",
        "altbeast5",
        "altbeast5d",
        "altbeast6",
        "dfjail",
        "eswatj1",
        "eswatjd",
        "exctleagd",
        "mvpj",
        "mvpjd",
        "riotcity",
    ], machines=["aurail","cotton","hwchamp"] },

    { name="sprites",       start="JTFRAME_BA3_START", width=16, reverse=true },
    { name="maincpu:key",   start="MAINKEY_START", len=0x2000 },
    { name="soundcpu:key",  start="SNDKEY_START", len=0x2000 },
    { name="fd1089",        start="FD1089_START" },
    { name="plds",          skip=true }
]
# { name="myregion", reorder=[3,2,1,0] } # reorder files inside a region
order = [
    "maincpu", "soundcpu", "gfx1",
    "sprites", "mcu", "maincpu:key", "soundcpu:key"
]
splits = [
    { machine="riotcity", region="sprites", offset=0x100000 },
    { machine="goldnaxe", region="sprites", offset=0x100000 },
    { setname="eswat",    region="sprites", offset=0x100000 },
    { setname="eswatj",   region="sprites", offset=0x100000 },
    { setname="eswatu",   region="sprites", offset=0x100000 },
    { machine="mvp",      region="sprites", offset=0x100000 },
    { machine="ultracin", region="sprites", offset=0x100000 },
    # Do not split
    { setname="eswatj1",  offset=0 },
    { setname="eswatj1d", offset=0 },
    { setname="mvpj",     offset=0 },
]

[header]
fill=0
# init_generic_5521 = 0
# init_hwchamp_5521 = 1
# init_altbeasj_5521 = 2
# init_altbeas4_5521 = 3
# init_shinobi4_5521 = 4
# init_generic_korean = 8
# init_snapper = 9
# init_lockonph = 0xa
# init_generic_5358        = 0x10
# init_generic_5358_small  = 0x11
# init_sdi_5358_small      = 0x12
# init_passshtj_5358       = 0x13
# init_dunkshot_5358_small = 0x14
# init_exctleag_5358       = 0x15
# init_aliensyn7_5358_small= 0x16
# init_aceattac_5358       = 0x17
# init_cencourt_5358       = 0x18
# init_defense_5358_small  = 0x19
# init_shinobi3_5358       = 0x1a
# init_sjryuko_5358_small  = 0x1b
# init_timescan_5358_small = 0x1c
#      afighter_analog     = 0x1d
# init_generic_5797        = 0x20
# init_generic_5704        = 0x40
# init_tturf_5704          = 0x41
# init_wb3_5704            = 0x42
# init_generic_bootleg = 0x80
# This must match the definitions in jts16b.def
data = [
    { offset=0x10, dev="fd1089a", data="01" },
    { offset=0x10, dev="fd1089b", data="02" },
    { offset=0x11, dev="fd1094",  data="01" },
    { offset=0x12, dev="mc8123",  data="01" },
    { offset=0x13, dev="i8751",   data="01" },

    { setname="aceattac",   offset=0x18, data="17" },
    { setname="aliensyn",   offset=0x18, data="11" },
    { setname="aliensyn7",  offset=0x18, data="11" }, # same as the others
    { setname="aliensyn3",  offset=0x18, data="11" },
    { setname="aliensynj",  offset=0x18, data="11" },
    { setname="afightere",  offset=0x18, data="1d" },
    { setname="afighterf",  offset=0x18, data="1d" },
    { setname="afighterg",  offset=0x18, data="11" },
    { setname="afighterh",  offset=0x18, data="11" },
    { setname="altbeast",   offset=0x18, data="00" },
    { setname="altbeastj",  offset=0x18, data="02" },
    { setname="altbeast6",  offset=0x18, data="00" },
    { setname="altbeast5",  offset=0x18, data="00" },
    { setname="altbeast4",  offset=0x18, data="03" },
    { setname="altbeastj3", offset=0x18, data="00" },
    { setname="altbeast2",  offset=0x18, data="03" },
    { setname="altbeastj1", offset=0x18, data="00" },
    { setname="aurail",     offset=0x18, data="40" },
    { setname="aurail1",    offset=0x18, data="40" },
    { setname="aurailj",    offset=0x18, data="40" },
    { setname="bayroute",   offset=0x18, data="40" },
    { setname="bayroutej",  offset=0x18, data="40" },
    { setname="bayroute1",  offset=0x18, data="10" },
    { setname="bullet",     offset=0x18, data="16" },
    { setname="cotton",     offset=0x18, data="40" },
    { setname="cottonu",    offset=0x18, data="40" },
    { setname="cottonj",    offset=0x18, data="40" },
    { setname="cottonja",   offset=0x18, data="40" },
    { setname="ddux",       offset=0x18, data="00" },
    { setname="dduxj",      offset=0x18, data="00" },
    { setname="ddux1",      offset=0x18, data="40" },
    { setname="dunkshot",   offset=0x18, data="14" },
    { setname="dunkshota",  offset=0x18, data="14" },
    { setname="dunkshoto",  offset=0x18, data="14" },
    { setname="eswat",      offset=0x18, data="20" },
    { setname="eswatu",     offset=0x18, data="20" },
    { setname="eswatj",     offset=0x18, data="20" },
    { setname="eswatj1",    offset=0x18, data="40" },
    { setname="exctleag",   offset=0x18, data="15" },
    { setname="fpoint",     offset=0x18, data="10" },
    { setname="fpoint1",    offset=0x18, data="40" },
    { setname="goldnaxe",   offset=0x18, data="20" },
    { setname="goldnaxeu",  offset=0x18, data="20" },
    { setname="goldnaxej",  offset=0x18, data="40" },
    { setname="goldnaxe3",  offset=0x18, data="40" },
    { setname="goldnaxe2",  offset=0x18, data="40" },
    { setname="goldnaxe1",  offset=0x18, data="20" },
    { setname="hwchamp",    offset=0x18, data="01" },
    { setname="hwchampj",   offset=0x18, data="01" },
    { setname="mvp",        offset=0x18, data="20" },
    { setname="mvpj",       offset=0x18, data="40" },
    { setname="passsht",    offset=0x18, data="10" },
    { setname="passshta",   offset=0x18, data="13" },
    { setname="passshtj",   offset=0x18, data="13" },
    { setname="cencourt",   offset=0x18, data="13" },
    { setname="riotcity",   offset=0x18, data="40" },
    { setname="ryukyu",     offset=0x18, data="40" },
    { setname="ryukyua",    offset=0x18, data="40" },
    { setname="defense",    offset=0x18, data="19" },
    { setname="sdib",       offset=0x18, data="19" },
    { setname="sdibl",      offset=0x18, data="12" },
    { setname="shinobi6",   offset=0x18, data="00" },
    { setname="shinobi5",   offset=0x18, data="10" },
    { setname="shinobi4",   offset=0x18, data="04" },
    { setname="shinobi3",   offset=0x18, data="1a" },
    { setname="shinobi2",   offset=0x18, data="10" },
    { setname="sonicbom",   offset=0x18, data="10" },
    { setname="sjryuko",    offset=0x18, data="1b" },
    { setname="suprleag",   offset=0x18, data="15" },
    { setname="tetris2",    offset=0x18, data="40" },
    { setname="tetris1",    offset=0x18, data="11" },
    { setname="timescan",   offset=0x18, data="1c" },
    { setname="toryumon",   offset=0x18, data="20" },
    { setname="tturf",      offset=0x18, data="41" },
    { setname="tturfu",     offset=0x18, data="10" },
    { setname="ultracin",   offset=0x18, data="20" },
    { setname="wb3",        offset=0x18, data="42" },
    { setname="wb34",       offset=0x18, data="40" },
    { setname="wb33",       offset=0x18, data="40" },
    { setname="wb32",       offset=0x18, data="10" },
    { setname="wrestwar",   offset=0x18, data="40" },
    { setname="wrestwar2",  offset=0x18, data="40" },
    { setname="wrestwar1",  offset=0x18, data="40" },
    { setname="fantzn2x",   offset=0x18, data="43" },
    { setname="fantzn2xp",  offset=0x18, data="43" },
    { setname="fantzoneta", offset=0x18, data="40" },
    { setname="atomicp",    offset=0x18, data="08" },
    { setname="snapper",    offset=0x18, data="09" },
    { setname="lockonph",   offset=0x18, data="0a" },
    { setname="dfjail",     offset=0x18, data="08" },
    { setname="shinobi2d",  offset=0x18, data="10" },
    { setname="fpointd",    offset=0x18, data="10" },
    { setname="fpoint1d",   offset=0x18, data="40" },
    { setname="tetris2d",   offset=0x18, data="40" },
    { setname="tetris1d",   offset=0x18, data="11" },
    { setname="dduxd",      offset=0x18, data="00" },
    { setname="dduxjd",     offset=0x18, data="00" },
    { setname="altbeast5d", offset=0x18, data="00" },
    { setname="altbeastj3d",offset=0x18, data="00" },
    { setname="aurail1d",   offset=0x18, data="40" },
    { setname="aurailjd",   offset=0x18, data="40" },
    { setname="mvpd",       offset=0x18, data="20" },
    { setname="mvpjd",      offset=0x18, data="40" },
    { setname="cottond",    offset=0x18, data="40" },
    { setname="cottonud",   offset=0x18, data="40" },
    { setname="cottonjad",  offset=0x18, data="40" },
    { setname="cottonjd",   offset=0x18, data="40" },
    { setname="bayrouted",  offset=0x18, data="40" },
    { setname="bayroutejd", offset=0x18, data="40" },
    { setname="exctleagd",  offset=0x18, data="15" },
    { setname="sonicbomd",  offset=0x18, data="10" },
    { setname="ryukyud",    offset=0x18, data="40" },
    { setname="hwchampjd",  offset=0x18, data="01" },
    { setname="bulletd",    offset=0x18, data="11" },
    { setname="eswatd",     offset=0x18, data="20" },
    { setname="eswatud",    offset=0x18, data="20" },
    { setname="eswatjd",    offset=0x18, data="20" },
    { setname="eswatj1d",   offset=0x18, data="40" },
    { setname="goldnaxeud", offset=0x18, data="20" },
    { setname="goldnaxe3d", offset=0x18, data="40" },
    { setname="goldnaxe1d", offset=0x18, data="20" },
    { setname="goldnaxejd", offset=0x18, data="40" },
    { setname="passshtd",   offset=0x18, data="10" },
    { setname="passshtad",  offset=0x18, data="13" },
    { setname="passshtjd",  offset=0x18, data="13" },
    { setname="wb34d",      offset=0x18, data="40" },
    { setname="wb33d",      offset=0x18, data="40" },
    { setname="wb32d",      offset=0x18, data="10" },
    { setname="wrestwar2d", offset=0x18, data="40" },
    { setname="wrestwar1d", offset=0x18, data="40" },
    { setname="sdibl2",     offset=0x18, data="12" },
    { setname="sdibl3",     offset=0x18, data="12" },
    { setname="sdibl4",     offset=0x18, data="12" },
    { setname="sdibl5",     offset=0x18, data="12" },
    { setname="sdibl6",     offset=0x18, data="12" }
]
