[global]
author=["jotego"]
platform="jtdd2"

[parse]
sourcefile=[ "ddragon.cpp" ]
skip.setnames=[
    "ddragon",
    "ddragonj",
    "ddragonja",
    "ddragona",
    "ddragonu",
    "ddragonua",
    "ddragonub",
    "ddragonbl2",
    "ddragonbl",
    "ddragonbla",
    "ddragon6809",
    "ddragon6809a",
    "tstrike",
    "tstrikea",

    # Bad rip-offs from other games
    # not worth the effort:
    "ddungeon",
    "ddungeone",
    "darktowr",
    "toffy",
    "toffya",
    "stoffy",
    "stoffyu",
]

[Audio]
volume = [
    { machine="ddragon2", value=0xFF },
]

[buttons]
Names = [
    { names="Left Attack,Jump,Right Attack"},
]

[dipsw]
# Flip screen not supported
delete=[{names=["Unused","Unknown"]}]
bitcnt = 16
rename = [
    { name="Bonus Life", to="Bonus" },
]

[ROM]
regions=[
    { name="maincpu", sequence=[1,2,3,3,4] },
    { name="soundcpu", no_offset=true, start="JTFRAME_BA1_START" },
    { name="chars", start="JTFRAME_BA2_START" }, # char
    { name="tiles", width=16, no_offset=true, start="SCR_START" }, # scroll
    { name="tiles", width=16, no_offset=true, sequence=[0,2,1,3], start="SCR_START", setname="ddragon2b" }, # scroll
    { name="sprites", width=16, no_offset=true, sequence=[0,3,1,4,2,5], start="JTFRAME_BA3_START" },  # objects
    { name="sprites", width=16, no_offset=true, sequence=[0,6,1,7,2,8,3,9,4,10,5,11], start="JTFRAME_BA3_START", setname="ddragon2b" },  # objects
    { name="sub", start="MCU_START" },
    { name="proms", files =[{ name="21j-k-0", size=256, crc="fdb130a9" }] } # the second PROM is not used
]

order=[
    "maincpu", "soundcpu",
    "oki",
    "chars", "tiles", "sprites", "sub",
    "proms"
]