[global]
author=["Solal Jacob"]
webpage="https://ko-fi.com/solalretrogaming"
twitter="@s_on_vg"

[parse]
sourcefile=["toki.cpp"]
skip.Setnames=["tokip"]
skip.bootlegs=true

[buttons]
names = [
    { names="Shoot,Jump" }
]

[dipsw]
# too long for MiST OSD:
delete=[
    { Names=["coinage"] }
]

[ROM]
regions=[
    { name="maincpu",  no_offset=true, width=16, reverse=true },
    { name="chars",    no_offset=true },
    { name="sprites",  no_offset=true },
    { name="bgtiles",  no_offset=true },
    { name="fgtiles",  no_offset=true },
    { name="audiocpu", no_offset=true },
    { name="oki",      no_offset=true },
    { name="proms",    no_offset=true },
]

order=[ "maincpu", "chars", "sprites", "bgtiles", "fgtiles", "audiocpu", "oki", "proms" ]
