[parse]
sourcefile=[ "namcos1.cpp" ]
skip = { machines=[
    # Key type 3
    "blastoff",
    "rompers", # hangs up after notice - vertical game
    "ws",      # needs 2-byte key ID
    "dangseed",
    "tankfrce",
    "pistoldm",

    # Others
    "bakutotu",
    "berabohm",
    "blazer",
    "boxyboy",
    "dspirit",
    "faceoff",
    "galaga88",
    "mmaze",
    "pacmania",
    "puzlclub",
    "quester",
    "shadowld",
    "wldcourt",
], setnames=[
    "ws90"
] }

[header]
info="""Byte 0: protection type
Byte 1: key ID
Byte 2: addr for key ID
Byte 3: addr for RNG
Byte 4: addr for nibble swap data write
Byte 5: addr for nibble swap read
"""
data= [
    { machine="splatter", data="03 B5 03 04" },
    { machine="blastoff", data="03 B7 00 07 03 05" },
    { setname="ws89",     data="03 B8 02 00" },
    # { machine="dangseed", data="03 34 01 06 ff 05 ff 00 04" },
    # { machine="rompers",  data="03 B6 07 00" },
]

[buttons]
names=[
    { machine="splatter", names="Attack,Jump" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]
rename=[
    # no idea about how to use these settings:
    {name="Open 3rd Life (step1of7)", to="3rd life 1/7"},
    {name="Open 3rd Life (step2of7)", to="3rd life 2/7"},
    {name="Open 3rd Life (step3of7)", to="3rd life 3/7"},
    {name="Open 3rd Life (step4of7)", to="3rd life 4/7"},
    {name="Open 3rd Life (step5of7)", to="3rd life 5/7"},
    {name="Open 3rd Life (step6of7)", to="3rd life 6/7"},
    {name="Open 3rd Life (step7of7)", to="3rd life 7/7"},
    {name="Auto Data Sampling (step1of2)", to="Data 1/2"},
    {name="Auto Data Sampling (step2of2)", to="Data 2/2"},
    {name="Draw Debug Lines (step1of6)", to="Debug lines 1/6"},
    {name="Draw Debug Lines (step2of6)", to="Debug lines 2/6"},
    {name="Draw Debug Lines (step3of6)", to="Debug lines 3/6"},
    {name="Draw Debug Lines (step4of6)", to="Debug lines 4/6"},
    {name="Draw Debug Lines (step5of6)", to="Debug lines 5/6"},
    {name="Draw Debug Lines (step6of6)", to="Debug lines 6/6"},
    {name="CPU #0 Kick Watchdog in IRQ (step1of2)", to="Debug IRQ 1/2"},
    {name="CPU #0 Kick Watchdog in IRQ (step2of2)", to="Debug IRQ 2/2"},
    {name="CPU #0&1 Kick Watchdog in IRQ (step1of2)", to="Debug IRQ 1/2"},
    {name="CPU #0&1 Kick Watchdog in IRQ (step2of2)", to="Debug IRQ 2/2"},
]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="user1" },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="voice",    start="PCM_START"  },
    { name="c123tmap:mask",    start="JTFRAME_BA2_START" },
    { name="c123tmap",         start="SCR_START", width=32 },
    { name="sprite",           start="JTFRAME_BA3_START", width=32 },
    { name="mcu",              start="JTFRAME_PROM_START"  },
]

order = [
    "user1", "audiocpu", "voice",
    "c123tmap:mask", "c123tmap", "sprite", "mcu"
]

# patches = [
#     # skip ROM check
#     { setname="xxx", offset=0x1058, data="12 11" }
# ]