[parse]
sourcefile=[ "namcos1.cpp" ]
skip = { machines=[ "puzlclub" ] }

debug = { machines=[
    # Key type 3
    "rompers",
    # Others
    "bakutotu",
    "berabohm",
    "boxyboy",
    "mmaze",
    "quester",
    "shadowld",
], setnames=[
    # key custom error (maybe related to being 4 players?)
    "tankfrcej",
    "tankfrce4",
] }

[buttons]
names = [
    # { machine="bakutotu",  names="" },
    # { machine="berabohm",  names="" },
    # { machine="blastoff",  names="" },
    # { machine="blazer",    names="" },
    # { machine="boxyboy",   names="" },
    # { machine="dangseed",  names="" },
    # { machine="dspirit",   names="" },
    # { machine="faceoff",   names="" },
    # { machine="galaga88",  names="" },
    # { machine="mmaze",     names="" },
    { machine="pacmania",  names="Jump" },
    # { machine="pistoldm",  names="" },
    # { machine="puzlclub",  names="" },
    # { machine="quester",   names="" },
    # { machine="rompers",   names="" },
    # { machine="shadowld",  names="" },
    { machine="splatter",  names="Attack,Jump" },
    # { machine="tankfrce",  names="" },
    # { machine="wldcourt",  names="" },
    # { machine="ws",        names="" },
]

[header]
info="""Byte 0: protection type
Byte 1: key ID
Byte 2: addr for key ID
Byte 3: addr for RNG
Byte 4: addr for nibble swap data write
Byte 5: addr for nibble swap read
Byte 6: addr for lower nibble read
Byte 7: addr for upper nibble read
"""
data= [
    { machine="dspirit",  data="01 36" },
    { machine="wldcourt", data="01 35" },
    { machine="blazer",   data="01 13" },
    { machine="puzlclub", data="01 35" },

    { machine="pacmania", data="02 12" },
    { machine="mmaze",    data="02 25" },
    { machine="galaga88", data="02 31" },
    { machine="ws",       data="02 07" },
    { machine="bakutotu", data="02 22" },

    { machine="splatter", data="03 B5 03 04 FF FF FF FF" },
    { machine="rompers",  data="03 B6 07 FF FF FF FF FF" },
    { machine="blastoff", data="03 B7 00 07 03 05 FF FF" },
    { setname="ws89",     data="03 B8 02 FF FF FF FF FF" },
    { machine="tankfrce", data="03 B9 05 FF 01 FF 02 FF" },
    { machine="dangseed", data="03 34 06 FF 05 FF 00 04" },
    { machine="pistoldm", data="03 35 01 02 00 FF 04 FF" },
    { machine="ws90",     data="03 36 04 FF 07 FF 03 FF" },
    { machine="boxyboy",  data="03 37 02 03 00 FF 04 FF" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]
rename=[
    # no idea about how to use these settings:
    {name="Open 3rd Life (step1of7)", to="3rd life 1/7"},
    {name="Open 3rd Life (step2of7)", to="3rd life 2/7"},
    {name="Open 3rd Life (step3of7)", to="3rd life 3/7"},
    {name="Open 3rd Life (step4of7)", to="3rd life 4/7"},
    {name="Open 3rd Life (step5of7)", to="3rd life 5/7"},
    {name="Open 3rd Life (step6of7)", to="3rd life 6/7"},
    {name="Open 3rd Life (step7of7)", to="3rd life 7/7"},
    {name="Auto Data Sampling (step1of2)", to="Data 1/2"},
    {name="Auto Data Sampling (step2of2)", to="Data 2/2"},
    {name="Draw Debug Lines (step1of6)", to="Debug lines 1/6"},
    {name="Draw Debug Lines (step2of6)", to="Debug lines 2/6"},
    {name="Draw Debug Lines (step3of6)", to="Debug lines 3/6"},
    {name="Draw Debug Lines (step4of6)", to="Debug lines 4/6"},
    {name="Draw Debug Lines (step5of6)", to="Debug lines 5/6"},
    {name="Draw Debug Lines (step6of6)", to="Debug lines 6/6"},
    {name="CPU #0 Kick Watchdog in IRQ (step1of2)", to="Debug IRQ 1/2"},
    {name="CPU #0 Kick Watchdog in IRQ (step2of2)", to="Debug IRQ 2/2"},
    {name="CPU #0&1 Kick Watchdog in IRQ (step1of2)", to="Debug IRQ 1/2"},
    {name="CPU #0&1 Kick Watchdog in IRQ (step2of2)", to="Debug IRQ 2/2"},
]

extra=[
    # Halt the sound CPU while YM2151 is busy. Not present in the original
    # Fixes issues in some games due to the poorly designed sound driver
    { name="*Sound fix", options="On,Off", bits="8" }
]

[ROM]
regions = [
    { name="user1" },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="voice",    start="PCM_START"  },
    { name="c123tmap:mask",    start="JTFRAME_BA2_START" },
    { name="c123tmap",         start="SCR_START"         },
    { name="sprite",           start="JTFRAME_BA3_START" },
    { name="mcu",              start="JTFRAME_PROM_START"  },
]

order = [
    "user1", "audiocpu", "voice",
    "c123tmap:mask", "c123tmap", "sprite", "mcu"
]

# patches = [
#     # skip ROM check
#     { setname="xxx", offset=0x1058, data="12 11" }
# ]