[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "tigeroad.cpp" ]
skip.bootlegs=true
skip.Setnames=["bballs","bballsa","pushman","pushmana", "pushmans", "pushmant","f1dream","f1dreamb","f1dreamba"]

[buttons]
names=[
    { names="Attack,Jump" },
]

[dipsw]
# Flip screen mode is not supported
delete=[ "Flip Screen", "Cabinet" ]

[ROM]
regions=[
    { name="maincpu", width=16, reverse=true },
    { name="bgmap", reverse=true, start="JTFRAME_BA1_START" },
    { name="audiocpu", start="JTFRAME_BA2_START" },
    { name="text",no_offset=true, start="JTFRAME_BA3_START", reverse=true },
    { name="tiles", sequence=[4,0,5,1,6,2,7,3], width=16, start="SCR_START" },
    { name="spritegen", width=32, reverse=true, no_offset=true },
]

order=[ "maincpu",
    "bgmap", "tiles",
    "audiocpu", "sample",
    "text", "spritegen",
    "proms"
]