[global]
mraauthor=["jotego"]

[parse]
sourcefile="lwings.cpp"
skip.Machines=[ "avengers", "trojan", "fball" ]

[buttons]
names=[
    { machine="sectionz", names="Shoot,Turn" },
    { machine="lwings", names="Shoot,Bomb" },
]

[header]
data=[ { machine="sectionz", offset=0, data="00" },
       { machine="lwings",   offset=0, data="01" } ]
offset={ bits=8, start=8, regions = ["soundcpu", "gfx1", "gfx2", "gfx3"]}

[dipsw]
rename=[ {name="Bonus Life", to="Bonus"}]

[ROM]
regions=[
    { name="maincpu", sequence=[1,2,0] },
    { name="gfx1" },
    { name="gfx5", reverse=true },
    { name="gfx2", width=32, sequence=[
        6,4,2,0,
        7,5,3,1
    ] },
    { name="gfx3", width=16, sequence=[
        0,2, 1,3 ] },
    { name="proms", skip=true },
]

order=[ "maincpu", "soundcpu", "adpcm",
    "gfx5", "gfx1", "gfx2",
    "gfx3"
]