[global]
author=["jotego"]

[parse]
sourcefile=[ "tmnt2.cpp", "asterix.cpp" ]
skip = { bootlegs=true, machines=[
	# in JTTMNT
	"tmnt",
	"mia",
	"punkshot",
	# not covered yet
	"blswhstl",
    "cuebrick",
    "lgtnfght",
    "blswhstl",
    "glfgreat",
    "qgakumon",
    "thndrx2",
    "prmrsocr",
    # ROM regions names
    "asterix",
]}

debug={machines=["tmnt2"]}

[buttons]
names = [
    { machine="ssriders", names="Shoot,Jump" },
    { machine="tmnt2",    names="Shoot,Jump" },
]

[header]
info="Offsets for each ROM region. Byte 15 = game selection."
data = [
	{ machine="ssriders", offset=15, data="00" },
	{ machine="tmnt2",    offset=15, data="01" },
]
offset = { bits=12, reverse=true, regions=["maincpu","audiocpu","k052109", "obj"] }

[ROM]
regions = [
    { name="maincpu", width=16, reverse=true  },

    { name="audiocpu"  },
    { name="k053260", rename="pcm", machines=[ "ssriders", "tmnt2" ]   },

    { name="k052109", width=32 }, # tiles
    # sprites
    { name="k053245", width=32, rename="obj", machines=[ "ssriders", "tmnt2" ] },
    { name="eeprom", skip=true }
]

order=["maincpu","audiocpu","pcm","k052109","obj"]

patches=[
	# skip the 54-frame wait after displaying the memory check
	{setname="ssriders",offset=0x1a40,data="71 4E 71 4E 71 4E 71 4E 71 4E 71 4E 71 4E 71 4E 71 4E 71 4E"},
	# skip wait after displaying the video grid
	{setname="ssriders",offset=0x1392,data="71 4E"},
]

# default configuration to prevent from boot-up error
nvram={	Defaults=[
	{ setname="ssriderseaa", data="""\
	00 00 01 01 01 01 FF 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 FF 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 F9 1D 90 64 45 41 41 00 06 E2"""},
	{ setname="ssridersjad", data="""\
	00 00 01 01 01 01 FF 00 00 00 00 00 00 00 00 00
	03 FF 00 03 01 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FA 13 90 64 4A 41 44 00 05 EC"""},
	{ setname="ssridersadd", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FB 19 90 64 41 44 44 00 04 E6"""},
	{ setname="ssridersjbd", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FB 12 90 64 4A 42 44 00 04 ED"""},
	{ setname="ssridersuac", data="""\
	00 00 01 01 01 01 FF 00 00 00 00 00 00 00 00 00
	03 FF 00 03 01 00 FF FF FF FF FF FF FF FF 00 00
	00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 F2 30 90 64 55 41 43 00 0D CF"""},
	{ setname="ssridersabd", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FB 1B 90 64 41 42 44 00 04 E4"""},
	{ setname="ssridersuda", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 FF FF FF FF FF FF FF FF 00 00
	00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 F3 2F 90 64 55 44 41 00 0C D0"""},
	{ setname="ssridersebc", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FB 18 90 64 45 42 43 00 04 E7"""},
	{ setname="ssridersubc", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 FF FF FF FF FF FF FF FF 00 00
	00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 F3 2F 90 64 55 42 43 00 0C D0"""},
	{ setname="ssridersjac", data="""\
	00 00 01 01 01 01 FF 00 00 00 00 00 00 00 00 00
	03 FF 00 03 01 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FA 14 90 64 4A 41 43 00 05 EB"""},
	{ setname="ssriders", data="""\
	00 00 01 01 01 01 FF 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FA 1A 90 64 45 41 43 00 05 E5"""},
	{ setname="ssridersebd", data="""\
	00 00 01 01 01 01 00 00 00 00 00 00 00 00 00 00
	03 FF 00 03 00 00 00 20 00 00 00 02 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 FB 17 90 64 45 42 44 00 04 E8"""},
	{ setname="ssridersuab", data="""\
	00 00 01 01 01 01 FF 00 00 00 00 00 00 00 00 00
	03 FF 00 03 01 00 FF FF FF FF FF FF FF FF 00 00
	00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 F2 31 90 64 55 41 42 00 0D CE"""},
	{ setname="tmht22pe", data="""\
	03 BE FC 41 90 63 45 42 41 00 00 00 00 01 01 01
	00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
	{ setname="tmnt2", data="""\
	03 CC FC 33 90 63 55 41 41 00 00 00 00 01 01 01
	00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
	{ setname="tmnt24pu", data="""\
	03 D1 FC 2E 90 63 55 45 41 00 00 00 00 01 01 01
	00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
	{ setname="tmnt22pu", data="""\
	03 CF FC 30 90 63 55 44 41 00 00 00 00 01 01 01
	00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
	{ setname="tmnt2a", data="""\
	03 BC FC 43 90 63 41 44 41 00 00 00 00 01 01 01
	00 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
	{ setname="tmht24pe", data="""\
	03 BC FC 43 90 63 45 41 41 00 00 00 00 01 01 01
	00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
	{ setname="tmnt2", data="""\
    03 cc fc 33 90 63 55 41 41 00 00 00 00 01 01 01
    00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
] }

