[global]
mraauthor=["jotego"]

[parse]
sourcefile="yiear.cpp"

[buttons]
names=[
    { names="Punch,Kick" }
]

[dipsw]
delete = [ "Unused", "Unknown" ]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", reverse=true },
    { name="tiles", width=16, no_offset=true }, # start=$GFX1_START
    { name="sprites", width=16, no_offset=true, Sort_even=true }, # start=$GFX2_START
    { name="vlm", reverse=true },
]

order = [
    "maincpu", "tiles", "sprites", "vlm", "proms"
]


