
name: tora for mister

on:
  push:
    branches:
      - build
      

jobs:

  mister_compilation:

    env:
      FTPUSER: ${{ secrets.FTPUSER }}
      FTPPASS: ${{ secrets.FTPPASS }}

    runs-on: ubuntu-latest

    container:
      image: jotego/jtcore:20
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: check out
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ github.repository }}
      - name: compile for mister
        run: /docked_build.sh tora -mister  
