
name: hige for mist

on:
  push:
    branches:
      - build
      - mist
      - build_hige
      - master

  workflow_dispatch:

  repository_dispatch:
    types: rebuild

jobs:

  mist_compilation:

    env:
      FTPUSER: ${{ secrets.FTPUSER }}
      FTPPASS: ${{ secrets.FTPPASS }}

    runs-on: ubuntu-latest

    container:
      image: jotego/jtcore13
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: check out
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ github.repository }}
      - name: Get YAML package
        run: go get gopkg.in/yaml.v2
      - name: compile for mist
        run: /docked_build.sh hige -mist  
