
name: gng for sidi

on:
  push:
    branches:
      - build
      - sidi
      - build_gng

  workflow_dispatch:

  repository_dispatch:
    types: rebuild

jobs:

  sidi_compilation:

    env:
      FTPUSER: ${{ secrets.FTPUSER }}
      FTPPASS: ${{ secrets.FTPPASS }}

    runs-on: ubuntu-latest

    container:
      image: jotego/jtcore13
      credentials:
        username: jotego
        password: ${{ secrets.DOCKER_LOGIN }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: check out
        uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ github.repository }}
      - name: compile for sidi
        run: /docked_build.sh gng -sidi  
